version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mentorarc
      - MYSQL_USER=mentorarc
      - MYSQL_PASSWORD=mentorarc
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  app:
    build: .
    ports:
      - 80:8081